import {
  ABSEvent,
  ALCState,
  AutopilotState,
  BSWState,
  CANData,
  ChargeCableState,
  FaultLampStatus,
  FCWState,
  Gear,
  LampFlashStatus,
  LatchStatus,
  LCHandsOnState,
  LDWState,
  LightRequest,
  LightStatus,
  LSSState,
  SCAState,
  SCIState,
  SCWState,
  SeatbeltBuckleStatus,
  SeatbeltChimeStatus,
  SwitchStatus,
  TrackModeState,
  TractionControlMode,
} from "./types";

export const canData: CANData = {
  airbagLight: false,
  das: {
    autoLaneChangeState: ALCState.ALC_SNA,
    autopilotHandsOnState: LCHandsOnState.SNA,
    autopilotState: AutopilotState.SNA,
    blindSpotRearLeft: BSWState.SNA,
    blindSpotRearRight: BSWState.SNA,
    forwardCollisionWarning: FCWState.SNA,
    laneDepartureWarning: LDWState.SNA,
    lssState: LSSState.OFF,
    sideCollisionAvoid: SCAState.SNA,
    sideCollisionInhibit: SCIState.NO_INHIBIT,
    sideCollisionWarning: SCWState.NONE,
  },
  di: {
    gear: Gear.SNA,
    trackModeState: TrackModeState.UNAVAILABLE,
    tractionControlMode: TractionControlMode.NORMAL,
    tcTelltaleOn: false,
    tcTelltaleFlash: false,
    vdcTelltaleOn: false,
    vdcTelltaleFlash: false,
    vehicleHoldTelltaleOn: false,
  },
  esp: {
    absBrakeEvent: ABSEvent.NOT_ACTIVE,
    absFaultLamp: FaultLampStatus.OFF,
    ebdFaultLamp: FaultLampStatus.OFF,
    espFaultLamp: FaultLampStatus.OFF,
    espLampFlash: LampFlashStatus.OFF,
    vehicleSpeed_kph: 1023,
  },
  gps: {
    accuracy_m: 0,
    latitude_deg: 0,
    longitude_deg: 0,
    vehicleHeading_deg: 0,
  },
  latchStatus: {
    VCFRONT_frunk: LatchStatus.SNA,
    VCLEFT_front: LatchStatus.SNA,
    VCLEFT_rear: LatchStatus.SNA,
    VCRIGHT_front: LatchStatus.SNA,
    VCRIGHT_rear: LatchStatus.SNA,
    VCRIGHT_trunk: LatchStatus.SNA,
  },
  lightStatus: {
    VCFRONT_DRLLeft: LightStatus.SNA,
    VCFRONT_DRLRight: LightStatus.SNA,
    VCFRONT_fogLeft: LightStatus.SNA,
    VCFRONT_fogRight: LightStatus.SNA,
    VCFRONT_highBeamLeft: LightStatus.SNA,
    VCFRONT_highBeamRight: LightStatus.SNA,
    VCFRONT_indicatorLeft: LightRequest.OFF,
    VCFRONT_indicatorRight: LightRequest.OFF,
    VCFRONT_lowBeamLeft: LightStatus.SNA,
    VCFRONT_lowBeamRight: LightStatus.SNA,
    VCFRONT_parkLeft: LightStatus.SNA,
    VCFRONT_parkRight: LightStatus.SNA,
    VCFRONT_sideMarkers: LightStatus.SNA,
    VCFRONT_sideRepeaterLeft: LightStatus.SNA,
    VCFRONT_sideRepeaterRight: LightStatus.SNA,
    VCFRONT_turnSignalLeft: LightStatus.SNA,
    VCFRONT_turnSignalRight: LightStatus.SNA,
    VCLEFT_brake: LightStatus.SNA,
    VCLEFT_dynamicBrake: LightRequest.OFF,
    VCLEFT_tail: LightStatus.SNA,
    VCLEFT_turnSignal: LightStatus.SNA,
    VCRIGHT_brake: LightStatus.SNA,
    VCRIGHT_rearFog: LightStatus.SNA,
    VCRIGHT_reverse: LightStatus.SNA,
    VCRIGHT_tail: LightStatus.SNA,
    VCRIGHT_turnSignal: LightStatus.SNA,
  },
  parkBrakeFault: false,
  power: {
    range_mi: 0,
    SOC_percent: 0,
    ratedWHpM: 0,
    systemPowerLimit_kW: 31,
    FrontPower_kW: 0,
    FrontHeatPower_kW: 0,
    FrontPowerLimit_kW: 0,
    RearPower_kW: 0,
    RearHeatPower_kW: 0,
    RearPowerLimit_kW: 0,
    SystemRegenPowerMax_kW: 0,
    SystemHeatPowerMax_kW: 0,
    SystemHeatPower_kW: 0,
    SystemDrivePowerMax_kW: 0,
    chargeCableState: ChargeCableState.UNKNOWN_SNA,
    chargeDoorOpen: false,
  },
  seatbeltStatus: {
    secondRowCenter: SeatbeltChimeStatus.SNA,
    secondRowLeft: SeatbeltChimeStatus.SNA,
    secondRowRight: SeatbeltChimeStatus.SNA,
    driverBuckle: SeatbeltBuckleStatus.UNBUCKLED,
    driver: SeatbeltChimeStatus.SNA,
    passenger: SeatbeltChimeStatus.SNA,
  },
  switchStatus: {
    swcLeftDoublePress: false,
    swcLeftPressed: SwitchStatus.SNA,
    swcLeftScrollTicks: 0,
    swcLeftTiltLeft: SwitchStatus.SNA,
    swcLeftTiltRight: SwitchStatus.SNA,
    swcRightDoublePress: false,
    swcRightPressed: SwitchStatus.SNA,
    swcRightScrollTicks: 0,
    swcRightTiltLeft: SwitchStatus.SNA,
    swcRightTiltRight: SwitchStatus.SNA,
  },
  tempAmbientFiltered_C: 0,
  tpms: {
    HardWarning: false,
    SoftWarning: false,
    OverPressureWarning: false,
    TemperatureWarning: false,
    SystemFault: false,
    FLpressure_bar: 0,
    FRpressure_bar: 0,
    RLpressure_bar: 0,
    RRpressure_bar: 0,
    FLtemp_degC: 0,
    FRtemp_degC: 0,
    RLtemp_degC: 0,
    RRtemp_degC: 0,
  },
  unixTimeSeconds: 0,
};

export default canData;
